version: '3.8'

services:
  client:
    build:
      context: ./client
      target: prod
    ports:
      - '80:80'

  server:
    build:
      context: ./server
      target: prod
    ports:
      - '3000:3000'
